"""Diff generation — create actual code patches from root cause analysis."""
import os
import re
from typing import Dict, List, Optional, Tuple
from datetime import datetime, timezone

from app.services.llm import generate_text


async def generate_patch(
    root_cause: Dict,
    affected_files: List[str],
    project_path: str = ".",
) -> Dict:
    """Generate a code patch based on root cause analysis."""
    system_prompt = """You are a code remediation expert. Given a root cause and affected files, generate a precise code patch.

Respond with JSON:
{
  "summary": "One-line description of the fix",
  "changes": [
    {
      "file": "path/to/file.py",
      "action": "modify|create|delete",
      "description": "What changed and why",
      "old_code": "exact code to replace (for modify)",
      "new_code": "replacement code",
      "line_start": 42,
      "line_end": 48
    }
  ],
  "commit_message": "fix: concise commit message",
  "risk": "low|medium|high",
  "risk_explanation": "why this risk level"
}

Rules:
- Be precise — match exact code from the file
- Minimal changes — fix only what's broken
- Preserve existing code style
- Include error handling if the fix touches error paths
- Don't refactor unrelated code"""

    files_context = []
    for fpath in affected_files[:5]:
        full_path = os.path.join(project_path, fpath)
        try:
            with open(full_path, "r", encoding="utf-8", errors="replace") as f:
                content = f.read(10000)
            files_context.append(f"FILE: {fpath}\n```\n{content}\n```")
        except FileNotFoundError:
            files_context.append(f"FILE: {fpath}\n[NOT FOUND]")

    user_prompt = f"""Root Cause: {root_cause.get('summary', 'Unknown')}
Causal Explanation: {root_cause.get('causal_explanation', 'N/A')}
Affected Component: {root_cause.get('affected_component', 'Unknown')}

Relevant Files:
{chr(10).join(files_context)}

Generate the minimal fix for this root cause."""

    try:
        from app.services.llm import generate_json
        result = await generate_json(system_prompt, user_prompt)
        return result
    except Exception as e:
        # Fallback: generate a basic patch structure
        return {
            "summary": f"Fix for: {root_cause.get('summary', 'Unknown issue')}",
            "changes": [
                {
                    "file": f,
                    "action": "modify",
                    "description": f"Apply fix for root cause: {root_cause.get('summary', '')}",
                    "old_code": "",
                    "new_code": "",
                    "line_start": 0,
                    "line_end": 0,
                }
                for f in affected_files[:3]
            ],
            "commit_message": f"fix: {root_cause.get('summary', 'resolve incident')[:72]}",
            "risk": "medium",
            "risk_explanation": "Generated by AI — requires human review",
        }


def generate_diff(old_code: str, new_code: str, file_path: str) -> str:
    """Generate a unified diff between old and new code."""
    old_lines = old_code.splitlines(keepends=True)
    new_lines = new_code.splitlines(keepends=True)

    diff_lines = [f"--- a/{file_path}\n", f"+++ b/{file_path}\n"]

    # Simple line-by-line diff
    max_len = max(len(old_lines), len(new_lines))
    for i in range(max_len):
        old_line = old_lines[i] if i < len(old_lines) else None
        new_line = new_lines[i] if i < len(new_lines) else None

        if old_line is None:
            diff_lines.append(f"+{new_line}")
        elif new_line is None:
            diff_lines.append(f"-{old_line}")
        elif old_line != new_line:
            diff_lines.append(f"-{old_line}")
            diff_lines.append(f"+{new_line}")

    return "".join(diff_lines)


def format_patch_for_pr(patch: Dict) -> str:
    """Format a patch dict into a PR-ready markdown description."""
    sections = []

    sections.append(f"## Summary\n\n{patch.get('summary', 'No summary')}\n")
    sections.append(f"## Commit Message\n\n`{patch.get('commit_message', 'fix: update')}`\n")
    sections.append(f"## Risk\n\n**{patch.get('risk', 'medium').upper()}** — {patch.get('risk_explanation', '')}\n")

    changes = patch.get("changes", [])
    if changes:
        sections.append("## Changes\n")
        for change in changes:
            sections.append(f"### `{change.get('file', 'unknown')}`\n")
            sections.append(f"**Action:** {change.get('action', 'modify')}\n")
            sections.append(f"**Description:** {change.get('description', '')}\n")
            if change.get("old_code") and change.get("new_code"):
                sections.append("```diff")
                sections.append(generate_diff(change["old_code"], change["new_code"], change.get("file", "")))
                sections.append("```\n")

    return "\n".join(sections)
