"""
Pydantic Schemas for Phase 8 Investigation Workflows.

Defines:
1. Strict structured schemas for untrusted LLM outputs (hypotheses, root causes, plans, abstentions).
2. API requests for workflow execution, stepping, pausing, cancelling, and single-use stream tickets.
3. API responses for detailed investigations and tasks.
4. Real-time workflow stream event payloads.
"""

import uuid
from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field, ConfigDict, field_validator

from app.models.incident import InvestigationStatus, TaskStatus, Confidence


# ============================================================================
# 1. UNTRUSTED LLM OUTPUT STRUCTURED SCHEMAS
# ============================================================================

class HypothesisOutput(BaseModel):
    """Structured hypothesis generated by LLM."""
    title: str = Field(..., max_length=255)
    description: str
    supporting_evidence_ids: List[str] = Field(default_factory=list)
    contradicting_evidence_ids: List[str] = Field(default_factory=list)
    confidence: float = Field(..., ge=0.0, le=1.0)
    test_strategy: Optional[str] = None


class RootCauseOutput(BaseModel):
    """Structured root cause identified by LLM."""
    summary: str
    component: str
    file_path: Optional[str] = None
    line_range: Optional[str] = None
    evidence_ids: List[str] = Field(default_factory=list)
    confidence: float = Field(..., ge=0.0, le=1.0)
    contradiction_analysis: Optional[str] = None


class RemediationPlanOutput(BaseModel):
    """Proposed remediation plan (non-mutating proposal)."""
    summary: str
    steps: List[str] = Field(default_factory=list)
    target_files: List[str] = Field(default_factory=list)
    proposed_diff: Optional[str] = None
    risk_level: str = "LOW"
    verification_strategy: Optional[str] = None


class AbstentionOutput(BaseModel):
    """Structured abstention explanation when confidence is low or evidence is lacking."""
    reason_code: str = "INSUFFICIENT_EVIDENCE"
    explanation: str
    missing_evidence: List[str] = Field(default_factory=list)
    contradictory_signals: List[str] = Field(default_factory=list)
    recommended_human_actions: List[str] = Field(default_factory=list)


# ============================================================================
# 2. API REQUEST SCHEMAS
# ============================================================================

class InvestigationStartRequest(BaseModel):
    """Request payload to initiate or resume an investigation."""
    workflow_type: Optional[str] = None
    lookback_window_minutes: int = 120
    override_params: Dict[str, Any] = Field(default_factory=dict)


class InvestigationStepRequest(BaseModel):
    """Request to execute a single discrete workflow step."""
    step_name: Optional[str] = None
    params: Dict[str, Any] = Field(default_factory=dict)


class StreamTicketResponse(BaseModel):
    """Short-lived, single-use ticket for secure SSE stream subscription."""
    stream_ticket: str
    investigation_id: uuid.UUID
    expires_in_seconds: int = 60


# ============================================================================
# 3. API RESPONSE SCHEMAS
# ============================================================================

class InvestigationTaskResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    investigation_id: uuid.UUID
    step_name: str
    task_type: str
    description: Optional[str] = None
    status: TaskStatus
    order: int
    tool_name: Optional[str] = None
    tool_input: Optional[Dict[str, Any]] = None
    tool_output: Optional[Dict[str, Any]] = None
    result_json: Optional[Dict[str, Any]] = None
    duration_ms: int = 0
    error_message: Optional[str] = None
    stepped_by_user_id: Optional[uuid.UUID] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    created_at: datetime


class EvidenceSummary(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: uuid.UUID
    title: str
    source_type: Optional[str] = None
    summary: Optional[str] = None
    file_path: Optional[str] = None
    repository: Optional[str] = None
    relevance_score: Optional[float] = None


class HypothesisSummary(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: uuid.UUID
    label: str
    description: Optional[str] = None
    confidence: Optional[str] = None
    status: Optional[str] = None
    supporting_evidence_count: int = 0
    contradicting_evidence_count: int = 0


class RootCauseSummary(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: uuid.UUID
    summary: str
    causal_explanation: Optional[str] = None
    confidence: Optional[str] = None
    affected_component: Optional[str] = None


class ProposedFixSummary(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: uuid.UUID
    title: str
    description: Optional[str] = None
    fix_type: Optional[str] = None
    status: Optional[str] = None
    diff: Optional[str] = None
    repository: Optional[str] = None


class InvestigationDetailResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    organization_id: uuid.UUID
    incident_id: Optional[uuid.UUID] = None
    work_item_id: Optional[uuid.UUID] = None
    workflow_type: str
    status: InvestigationStatus
    current_step: Optional[str] = None
    current_step_index: int = 0
    total_steps: int = 1
    progress_percent: int = 0

    root_cause_found: bool = False
    abstained: bool = False
    abstention_reason: Optional[str] = None
    security_case_id: Optional[str] = None
    confidence: Optional[Confidence] = None
    base_commit_sha: Optional[str] = None

    llm_model: Optional[str] = None
    total_tokens: int = 0
    total_cost_usd: float = 0.0
    plan_json: Optional[Dict[str, Any]] = None
    logs_json: Optional[List[Dict[str, Any]]] = None
    evidence_snapshot_id: Optional[str] = None
    started_by_user_id: Optional[uuid.UUID] = None

    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    created_at: datetime
    updated_at: Optional[datetime] = None
    tasks: List[InvestigationTaskResponse] = Field(default_factory=list)
    evidence: List[EvidenceSummary] = Field(default_factory=list)
    hypotheses: List[HypothesisSummary] = Field(default_factory=list)
    root_causes: List[RootCauseSummary] = Field(default_factory=list)
    proposed_fixes: List[ProposedFixSummary] = Field(default_factory=list)


# ============================================================================
# 4. SSE STREAM EVENT PAYLOAD
# ============================================================================

class WorkflowStreamEvent(BaseModel):
    """Event emitted across SSE stream."""
    event_id: int
    timestamp: str
    event_type: str  # "step_started" | "log" | "step_completed" | "workflow_finished" | "workflow_failed" | "abstained" | "paused" | "heartbeat"
    step_name: Optional[str] = None
    message: str
    progress_percent: int = 0
    data: Dict[str, Any] = Field(default_factory=dict)
